export enum InsightRoutes {
  addUser = '/api/users/add',
  getAccounts = '/api/accounts',
  getAllTransactions = '/api/transactions/all',
  getBudgets = '/api/budgets',
  getBudgetYears = '/api/budget/years',
  getCategories = '/api/categories',
  getPayees = '/api/payees',
  getTransactionsByDay = '/api/transactions/aggregate',
  getTransactionsByPayee = '/api/transactions/payee',
  reportsMonthly = '/api/reports/monthly',
  syncAccounts = '/api/sync/accounts',
  syncBudgets = '/api/sync/budgets',
  syncCategories = '/api/sync/categories',
  syncPayees = '/api/sync/payees',
  syncTransactions = '/api/sync/transactions',
  users = '/api/users',
}
